# Generated by Django 4.1.5 on 2023-01-09 13:59

from django.db import migrations, models
import helpers.model


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoryItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(default='story', max_length=10, verbose_name='Type')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('descendants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Descendants')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score')),
            ],
            bases=(models.Model, helpers.model.ItemBaseModel),
        ),
    ]
