# Generated by Django 4.1.5 on 2023-01-09 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storyitemmodel',
            options={'verbose_name': 'Story', 'verbose_name_plural': 'Stories'},
        ),
    ]
