# Generated by Django 4.1.5 on 2023-01-09 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='storyitemmodel',
            table='items_tb',
        ),
    ]
