# Generated by Django 4.1.5 on 2023-01-09 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_storyitemmodel_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitemmodel',
            name='by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='storyitemmodel',
            name='dead',
            field=models.BooleanField(default=False, null=True, verbose_name='Dead'),
        ),
        migrations.AddField(
            model_name='storyitemmodel',
            name='deleted',
            field=models.BooleanField(default=False, null=True, verbose_name='Deleted'),
        ),
        migrations.AddField(
            model_name='storyitemmodel',
            name='kids',
            field=models.TextField(blank=True, null=True, verbose_name='Kids'),
        ),
        migrations.AddField(
            model_name='storyitemmodel',
            name='time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
