# Generated by Django 4.1.5 on 2023-01-09 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_storyitemmodel_by_storyitemmodel_dead_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storyitemmodel',
            name='hnId',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='HackerNews Id'),
        ),
    ]
