# Generated by Django 4.1.5 on 2023-01-10 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('news', '0003_delete_storyitemmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemBaseModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hnId', models.PositiveIntegerField(blank=True, null=True, verbose_name='HackerNews Id')),
                ('type', models.CharField(choices=[('JOB', 'job'), ('STORY', 'story'), ('COMMENT', 'comment')], default='STORY', max_length=10, verbose_name='Type')),
                ('by', models.CharField(blank=True, max_length=100, null=True, verbose_name='Author')),
                ('deleted', models.BooleanField(default=False, null=True, verbose_name='Deleted')),
                ('dead', models.BooleanField(default=False, null=True, verbose_name='Dead')),
                ('time', models.DateTimeField(blank=True, null=True)),
                ('kids', models.TextField(blank=True, null=True, verbose_name='Kids')),
                ('title', models.CharField(blank=True, max_length=225, null=True, verbose_name='Title')),
                ('url', models.URLField(blank=True, null=True, verbose_name='Url')),
                ('descendants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Descendants')),
                ('score', models.PositiveIntegerField(blank=True, null=True, verbose_name='Score')),
                ('text', models.CharField(blank=True, max_length=225, null=True, verbose_name='Text')),
                ('parent', models.PositiveIntegerField(blank=True, null=True, verbose_name='Parent')),
            ],
            options={
                'db_table': 'items_tb',
            },
        ),
        migrations.CreateModel(
            name='CommentItemModel',
            fields=[
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
                'abstract': False,
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.itembasemodel',),
        ),
        migrations.CreateModel(
            name='StoryItemModel',
            fields=[
            ],
            options={
                'verbose_name': 'Story',
                'verbose_name_plural': 'Stories',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('news.itembasemodel',),
        ),
    ]
