# Generated by Django 4.1.5 on 2023-01-10 03:07

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_itembasemodel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembasemodel',
            name='kids',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')], verbose_name='Kids'),
        ),
    ]
