# Generated by Django 4.1.5 on 2023-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_itembasemodel_kids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembasemodel',
            name='kids',
            field=models.TextField(blank=True, null=True, verbose_name='Kids'),
        ),
    ]
